cookie:
  expiry_days: 30
  key: random_signature_key
  name: financial_advisor_dashboard
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$AIM3qmKo4o6OSfQiod9VqO7/njL9KlyojLouDcwPfIrvGefOtD5Wu
    advisor:
      email: advisor@example.com
      name: Financial Advisor
      password: $2b$12$8anfnTITQz8NNLh0ssmjgun61iCnZ4NMS1sSoqztHj4Q7sl4tS0s2
    analyst:
      email: analyst@example.com
      name: Financial Analyst
      password: $2b$12$486D1XnFjpQYCf/jVXAgF.cUkH.OXOOnFaM9ayFcmTgxx2zyQQSD2
