cookie:
  expiry_days: 30
  key: random_signature_key
  name: financial_advisor_dashboard
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$UhmUaKPp4wFJ2gUXGYxlXuc7ltA0TtineblnVz.RRjFzVNxr667Oq
    advisor:
      email: advisor@example.com
      name: Financial Advisor
      password: $2b$12$NzxPnxFeLBdMsBtxEvgele0utGTWzoSmI1njHPumwM194IBqb5EPq
    analyst:
      email: analyst@example.com
      name: Financial Analyst
      password: $2b$12$rNTc6MJYBlLFT.QUy7jz7eXH880dRp0wjtyHrWAl1Mb6id4u.XBhm
