cookie:
  expiry_days: 30
  key: random_signature_key
  name: financial_advisor_dashboard
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$j.uCPshcZ95VZzuhtB6QUu7/nJSNxxY0nnLgUMfvk/Dt5dmVU2ejy
    advisor:
      email: advisor@example.com
      name: Financial Advisor
      password: $2b$12$RfVb/iLwEwya0GCkzHw3s.gNnYbSE3Ex3qeiD.u196FR3t3VvhllO
    analyst:
      email: analyst@example.com
      name: Financial Analyst
      password: $2b$12$RnMDLvp3qloz9c3axOYkVO8H/nXTBc5ZgyklqZLj5o6gvz4OuK3US
